---
output:
  pdf_document: default
---

```{r include = F}
# Never remove raw data, only expand on the .csv-file

# Load necessary packages
library(markdown)
library(tidyverse)
library(knitr)

# Clear workspace
rm(list=ls())

# Read in starting data & replace different ways of NA with a logical NA (ugly done, maybe by using regex it could be more elegantly done)
setwd("H:/data/co2-splitting/uhasselt/SiO2@Anatase TiO2-220-09H")
filename <- "res-time-10.0s-2.csv"
data <- read_csv(filename, na = c("NA", "na", "Na", "nA", "N A", "N/A", "N a", "n A", "n a"))

#######################################################################################################################
# calculate average concentration, standard deviation, and relative standard deviation for each compound in each test #
#######################################################################################################################

# na.rm = T is added to ignore NA's
data <- data %>%
  group_by(state, compound) %>%
  mutate(conc_avg = mean(conc, na.rm = T),
         conc_sd  = sd(conc, na.rm = T),
         conc_rsd = conc_sd / conc_avg,
         .after = conc) %>%
  ungroup()

#################################################################
# calculate beta and its standard & relative standard deviation #
#################################################################

# Note 1: 0.005 is the reading accuracy of the F-201CV MFCs & 0.001 is the full scale value of the F-201CV MFCs (you can find these values on the product page of the MFCs of your choice),
#         all flow (so +/- 100% of flow values according to normal distribution) fall between the sumation for these two errors.

# Note 2: 3.890592 is the z-value for which 99.99% of values fall within a normal curve.

# Note 3: their is no error on beta, as any error from the error on gas flow is indirectly present in the measured concentrations by the GC

data <- mutate(data,
               flow_mlmin_sd  = (.005 * flow_mlmin + .001 * flow_max_mlmin) / qnorm(.99995),
               flow_rsd = flow_mlmin_sd / flow_mlmin,
               .after = flow_max_mlmin)

# select average N2 concentrations from blank experiment
conc_avg_n2_blank <- data %>%
  filter(state == "blank" & compound == "N2") %>%
  pull(conc_avg) %>%
  unique()

# Select average CO2 concentration from blank experiment
conc_avg_co2_blank <- data %>%
  filter(state == "blank" & compound == "CO2") %>%
  pull(conc_avg) %>%
  unique()

# calculating beta as the ratio between the concentration of N2 and CO2 as measured by the GC, corrects for the pressure drop across the (packed) reactor (is assume)

beta <- conc_avg_n2_blank / conc_avg_co2_blank
beta_sd <- 0
beta_rsd <- 0

data <- mutate(data,
               beta     = beta,
               beta_sd  = beta_sd,
               beta_rsd = beta_rsd,
               .after = conc_rsd)

##################################################################
# calculate alpha and its standard & relative standard deviation #
##################################################################

# Firstly, we pull all the necessary numbers for the calculations

# select relative standard deviation of the N2 concentration from the blank experiment
conc_avg_n2_blank_rsd <- data %>%
  filter(state == "blank" & compound == "N2") %>%
  pull(conc_rsd) %>%
  unique()

# select average N2 concentrations from plasma experiment
conc_avg_n2_plasma <- data %>%
  filter(state == "plasma" & compound == "N2") %>%
  pull(conc_avg) %>%
  unique()

# select relative standard deviation of the N2 concentration from the plasma
conc_avg_n2_plasma_rsd <- data %>%
  filter(state == "plasma" & compound == "N2") %>%
  pull(conc_rsd) %>%
  unique()

# Secondly, we calculate alpha and set its SD and RSD to 0 (the error on alpha is indirectly present in the error on the concentrations determined by the GC)
# For the blank experiments alpha is equal to 1 (there is no gas expansion)

data <- mutate(data,
               alpha     = ifelse(state == "blank", 1, conc_avg_n2_blank / conc_avg_n2_plasma * (1 + beta) - beta),
               alpha_sd  = 0,
               alpha_rsd = 0,
               .after = conc_rsd)

# From the data, obtain alpha and its RSD
# (if something goes wrong with the internal standard/GC and alpha is lower than one, it is automatically replaced by a 1)

alpha <- data %>%
  filter(state == "plasma") %>%
  pull(alpha) %>%
  unique() %>%
  ifelse(. < 1, 1, .)

alpha_sd <- 0

alpha_rsd <- 0

########################################################
# calculate corrected concentrations for the compounds #
########################################################

# Calculation of the corrected average concentrations of CO2, CO, and O2 entering and leaving the reactor
# and the N2 concentration upon addition as internal standard
# This correction however, has no physical meaning for N2, so to avoid confusion, we'll delete is for N2

data <- mutate(data,
               conc_avg_corr     = ifelse(compound == "N2", NA, conc_avg * (1 + beta / alpha)),
               conc_avg_corr_sd  = ifelse(compound == "N2", NA, sqrt(
                 (beta_rsd ^ 2 + alpha_rsd ^ 2)
                 *
                 (beta / alpha) ^ 2
                 /
                 (1 + beta / alpha) ^ 2
                 +
                 conc_rsd ^ 2) * conc_avg_corr),
               conc_avg_corr_rsd = ifelse(compound == "N2", NA, conc_avg_corr_sd / conc_avg_corr),
               .after = conc_rsd)

##########################
# Calculating conversion # in this case only for CO2
##########################

# Obtain also the corrected concentration of CO2 in the blank measurement and its RSD

conc_avg_corr_co2_blank <- data %>%
  filter(state == "blank" & compound == "CO2") %>%
  pull(conc_avg_corr) %>%
  unique()

conc_avg_corr_co2_blank_rsd <- data %>%
  filter(state == "blank" & compound == "CO2") %>%
  pull(conc_avg_corr_rsd) %>%
  unique()

# Obtain also the corrected concentration of CO2 in the plasma measurement and its RSD

conc_avg_corr_co2_plasma <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  pull(conc_avg_corr) %>%
  unique()

conc_avg_corr_co2_plasma_rsd <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  pull(conc_avg_corr_rsd) %>%
  unique()

# Calculate the CO2 conversion from these numbers

conv_co2 <- 1 - alpha * (conc_avg_corr_co2_plasma / conc_avg_corr_co2_blank)

# Calculate the standard deviation on the CO2 conversion

conv_co2_sd <- sqrt(conc_avg_corr_co2_blank_rsd ^ 2 + conc_avg_corr_co2_plasma_rsd ^ 2 + alpha_rsd ^ 2) *
  alpha *
  (conc_avg_corr_co2_plasma / conc_avg_corr_co2_blank)

# Calculate the relative standard deviation on the CO2 conversion

conv_co2_rsd <- conv_co2_sd / conv_co2

# Add these numbers for CO2 to the data

data <- mutate(data,
               conv     = ifelse(compound == "CO2" & state == "plasma", conv_co2, NA),
               conv_sd  = ifelse(compound == "CO2" & state == "plasma", conv_co2_sd, NA),
               conv_rsd = ifelse(compound == "CO2" & state == "plasma", conv_co2_rsd, NA),
               .after = beta_rsd)

###################
# Carbon Monoxide #
###################

# Carbon selectivity #
######################

# Alpha and its RSD have already been obtained and are put in the alpha & alpha_rsd objects

# The corrected concentration of CO2 in the blank measurements is put in conc_avg_corr_co2_blank

# The standard deviation on the corrected CO2 concentration for blank measurements must still be obtained

conc_avg_corr_co2_blank_sd <- data %>%
  filter(state == "blank" & compound == "CO2") %>%
  pull(conc_avg_corr_sd) %>%
  unique()

# The corrected concentration of CO2 from the plasma measurements is put in conc_avg_corr_co2_plasma

# The relative standard deviation on the corrected CO2 concentration for the plasma measurements is put in the object concavg_corr_co2_plasma_rsd

# From the data, the concentration of CO in plasma experiments must be obtained

conc_avg_corr_co <- data %>%
  filter(state == "plasma" & compound == "CO") %>%
  pull(conc_avg_corr) %>%
  unique()

# From the data, the RSD of the corrected CO concentration must also be obtained

conc_avg_corr_co_rsd <- data %>%
  filter(state == "plasma" & compound == "CO") %>%
  pull(conc_avg_corr_rsd) %>%
  unique()

# The carbon selectivity of CO can be calculated as follows

selec_c_co <- (alpha * conc_avg_corr_co) / (conc_avg_corr_co2_blank - alpha * conc_avg_corr_co2_plasma)

# The RSD of the carbon selectivity of CO can be calculated as follows

selec_c_co_rsd <- sqrt(
  (alpha_rsd ^ 2 + conc_avg_corr_co_rsd ^ 2)
  +
    (
      ((alpha_rsd ^ 2 + conc_avg_corr_co2_plasma_rsd ^ 2) * alpha ^ 2 * conc_avg_corr_co2_plasma ^ 2 + conc_avg_corr_co2_blank_sd ^ 2)
      /
      (conc_avg_corr_co2_blank - alpha * conc_avg_corr_co2_plasma) ^ 2
    )
)

# The SD of the carbon selectivity of CO can be calculated then as follows

selec_c_co_sd <- selec_c_co_rsd * selec_c_co

# Add these numbers to the data

data <- mutate(data,
               selec_c     = ifelse(compound == "CO" & state == "plasma", selec_c_co, NA),
               selec_c_sd  = ifelse(compound == "CO" & state == "plasma", selec_c_co_sd, NA),
               selec_c_rsd = ifelse(compound == "CO" & state == "plasma", selec_c_co_rsd, NA),
               .after = conv_rsd)

# Carbon yield #
################

# These calculations are simplified by the fact that the carbon yield of CO is the product
# of the conversion of CO2 and the selectivity of CO, both numbers which are already
# stored in objects, just like their SD and RSD

yield_c_co <- conv_co2 * selec_c_co

yield_c_co_rsd <- sqrt(conv_co2_rsd ^ 2 + selec_c_co_rsd ^ 2)

yield_c_co_sd <- yield_c_co_rsd * yield_c_co

# Add these numbers to the data

data <- mutate(data,
               yield_c     = ifelse(compound == "CO" & state == "plasma", yield_c_co, NA),
               yield_c_sd  = ifelse(compound == "CO" & state == "plasma", yield_c_co_sd, NA),
               yield_c_rsd = ifelse(compound == "CO" & state == "plasma", yield_c_co_rsd, NA),
               .after = selec_c_rsd)

# Oxygen selectivity #
######################

# Alpha and its RSD have already been obtained and are put in the alpha & alpha_rsd objects

# The corrected concentration of CO2 in the blank measurements is put in conc_avg_corr_co2_blank

# The standard deviation on the corrected CO2 concentration for blank measurements is put in the object conc_avg_corr_co2_blank_sd

# The corrected concentration of CO2 from the plasma measurements is put in conc_avg_corr_co2_plasma

# The relative standard deviation on the corrected CO2 concentration for the plasma measurements is put in the object conc_avg_corr_co2_plasma_rsd

# The concentration of CO in plasma experiments is put in the object conc_avg_corr_co

# The RSD of the corrected CO concentration is put in object conc_avg_corr_co_rsd


# The oxygen selectivity of CO can be calculated as follows

selec_o_co <- (alpha * conc_avg_corr_co) / (2 * (conc_avg_corr_co2_blank - alpha * conc_avg_corr_co2_plasma))

# The RSD of the oxygen selectivity of CO can be calculated as follows

selec_o_co_rsd <- sqrt(
  (alpha_rsd ^ 2 + conc_avg_corr_co_rsd ^ 2)
  +
  (
    ((alpha_rsd ^ 2 + conc_avg_corr_co2_plasma_rsd ^ 2) * alpha ^ 2 * conc_avg_corr_co2_plasma ^ 2 + conc_avg_corr_co2_blank_sd ^ 2)
    /
    (conc_avg_corr_co2_blank - alpha * conc_avg_corr_co2_plasma) ^ 2
  )
                      )

# The SD of the CO selectivity can be calculated then as follows

selec_o_co_sd <- selec_o_co_rsd * selec_o_co

# Add these numbers to the data

data <- mutate(data,
               selec_o     = ifelse(compound == "CO" & state == "plasma", selec_o_co, NA),
               selec_o_sd  = ifelse(compound == "CO" & state == "plasma", selec_o_co_sd, NA),
               selec_o_rsd = ifelse(compound == "CO" & state == "plasma", selec_o_co_rsd, NA),
               .after = yield_c_rsd)

# Oxygen yield #
################

# These calculations are simplified by the fact that the oxygen yield of CO is the product
# of the conversion of CO2 and the oxygen selectivity of CO, both numbers which are already
# stored in objects, just like their SD and RSD

yield_o_co <- conv_co2 * selec_o_co

yield_o_co_rsd <- sqrt(conv_co2_rsd ^ 2 + selec_o_co_rsd ^ 2)

yield_o_co_sd <- yield_o_co_rsd * yield_o_co

# Add these numbers to the data

data <- mutate(data,
               yield_o     = ifelse(compound == "CO" & state == "plasma", yield_o_co, NA),
               yield_o_sd  = ifelse(compound == "CO" & state == "plasma", yield_o_co_sd, NA),
               yield_o_rsd = ifelse(compound == "CO" & state == "plasma", yield_o_co_rsd, NA),
               .after = selec_o_rsd)

##########
# Oxygen #
##########

# Oxygen selectivity #
######################

# Alpha and its RSD have already been obtained and are put in the alpha & alpha_rsd objects

# The corrected concentration of CO2 in the blank measurements is put in conc_avg_corr_co2_blank

# The standard deviation on the corrected CO2 concentration for blank measurements is put in the object conc_avg_corr_co2_blank_sd

# The corrected concentration of CO2 from the plasma measurements is put in conc_avg_corr_co2_plasma

# The relative standard deviation on the corrected CO2 concentration for the plasma measurements is put in the object conc_avg_corr_co2_plasma_rsd

# The concentration of O2 in plasma experiments is put in the object conc_avg_corr_o2

conc_avg_corr_o2 <- data %>%
  filter(state == "plasma" & compound == "O2") %>%
  pull(conc_avg_corr) %>%
  unique()

# The RSD of the corrected O2 concentration is put in object conc_avg_corr_o2_rsd

conc_avg_corr_o2_rsd <- data %>%
  filter(state == "plasma" & compound == "O2") %>%
  pull(conc_avg_corr_rsd) %>%
  unique()

# The oxygen selectivity of O2 can be calculated as follows

selec_o_o2 <- (alpha * conc_avg_corr_o2) / (conc_avg_corr_co2_blank - alpha * conc_avg_corr_co2_plasma)

# The RSD of the oxygen selectivity of O2 can be calculated as follows

selec_o_o2_rsd <- sqrt(
  (alpha_rsd ^ 2 + conc_avg_corr_o2_rsd ^ 2)
  +
  (
   ((alpha_rsd ^ 2 + conc_avg_corr_co2_plasma_rsd ^ 2) * alpha ^ 2 * conc_avg_corr_co2_plasma ^ 2 + conc_avg_corr_co2_blank_sd ^ 2)
    /
   (conc_avg_corr_co2_blank - alpha * conc_avg_corr_co2_plasma) ^ 2
  )
                      )

# The SD of the oxygen selectivity of O2 can be calculated then as follows

selec_o_o2_sd <- selec_o_o2_rsd * selec_o_o2

# Add these numbers to the data

data <- mutate(data,
               selec_o     = ifelse(compound == "O2" & state == "plasma", selec_o_o2, selec_o),
               selec_o_sd  = ifelse(compound == "O2" & state == "plasma", selec_o_o2_sd, selec_o_sd),
               selec_o_rsd = ifelse(compound == "O2" & state == "plasma", selec_o_o2_rsd, selec_o_rsd))

# Calculating the oxygen yield of O2 #
######################################

# These calculations are simplified by the fact that the oxygen yield of O2 is the product
# of the conversion of CO2 and the oxygen selectivity of O2, both numbers which are already
# stored in objects, just like their SD and RSD

yield_o_o2 <- conv_co2 * selec_o_o2

yield_o_o2_rsd <- sqrt(conv_co2_rsd ^ 2 + selec_o_o2_rsd ^ 2)

yield_o_o2_sd <- yield_o_o2_rsd * yield_o_o2

# Add these numbers to the data

data <- mutate(data,
               yield_o     = ifelse(compound == "O2" & state == "plasma", yield_o_o2, yield_o),
               yield_o_sd  = ifelse(compound == "O2" & state == "plasma", yield_o_o2_sd, yield_o_sd),
               yield_o_rsd = ifelse(compound == "O2" & state == "plasma", yield_o_o2_rsd, yield_o_rsd))

#####################################
# CO:O2 yield ratio (should be 2:1) #
#####################################

# Calculation of the yield ratio

yield_ratio <- yield_c_co / yield_o_o2

# Calculation of the RSD of the ratio

yield_ratio_rsd <- sqrt(yield_c_co_rsd ^ 2 + yield_o_o2_rsd ^ 2)

# Calculation of the SD of the ratio

yield_ratio_sd <- yield_ratio_rsd * yield_ratio

# Add these numbers to the data

data <- mutate(data,
               yield_ratio     = yield_ratio,
               yield_ratio_sd  = yield_ratio_sd,
               yield_ratio_rsd = yield_ratio_rsd,
               .after = yield_o_rsd)

##################
# Carbon Balance #
##################

# Calculation of the carbon balance

balance_c <- (alpha * (conc_avg_corr_co + conc_avg_corr_co2_plasma)) / conc_avg_corr_co2_blank

# From the data, the SD of the corrected CO concentration must also be obtained

conc_avg_corr_co_sd <- data %>%
  filter(state == "plasma" & compound == "CO") %>%
  pull(conc_avg_corr_sd) %>%
  unique()

# From the data, the SD for the corrected CO2 concentration after plasma must be taken

conc_avg_corr_co2_plasma_sd <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  pull(conc_avg_corr_sd) %>%
  unique()

# Calculation of the RSD of the C-balance

balance_c_rsd <- sqrt(alpha_rsd ^ 2 + conc_avg_corr_co2_blank_rsd ^ 2 +
  ((conc_avg_corr_co_sd ^ 2 + conc_avg_corr_co2_plasma_sd) / (conc_avg_corr_co + conc_avg_corr_co2_plasma) ^ 2))

# Calculation of the SD of the C-balance

balance_c_sd <- balance_c_rsd * balance_c

data <- mutate(data,
               balance_c     = balance_c,
               balance_c_sd  = balance_c_sd,
               balance_c_rsd = balance_c_rsd,
               .after = yield_ratio_rsd)

##################
# Oxygen Balance #
##################

# Calculation of the oxygen balance

balance_o <- (alpha * (2 * conc_avg_corr_o2 + 1 * conc_avg_corr_co + 2 * conc_avg_corr_co2_plasma)) / (2 * conc_avg_corr_co2_blank)

# From the data, the SD of the corrected O2 concentration must also be obtained

conc_avg_corr_o2_sd <- data %>%
  filter(state == "plasma" & compound == "O2") %>%
  pull(conc_avg_corr_sd) %>%
  unique()

# Calculation of the RSD of the oxygen balance

balance_o_rsd <- sqrt(conc_avg_corr_co2_blank_rsd ^ 2 + alpha_rsd ^ 2 +
  ((2 ^ 2 * conc_avg_corr_o2_sd ^ 2 + 1 ^ 2 * conc_avg_corr_co_sd ^ 2 + 2 ^ 2 * conc_avg_corr_co2_plasma_sd)
  /
  (2 * conc_avg_corr_o2 + conc_avg_corr_co + 2 * conc_avg_corr_co2_plasma) ^ 2)
                     )

# Calculation of the SD of the O-balance

balance_o_sd <- balance_o_rsd * balance_o

# Adding values to the data

data <- mutate(data,
               balance_o     = balance_o,
               balance_o_sd  = balance_o_sd,
               balance_o_rsd = balance_o_rsd,
               .after = balance_c_rsd)

###############################
# Specific Energy Input (SEI) #
###############################

# Calculation the average plasma power, its SD and its RSD

data <- data %>%
  group_by(state, compound) %>%
  mutate(plasma_power_watt_avg = ifelse(state == "blank", NA, mean(plasma_power_watt, na.rm = T)),
         plasma_power_watt_sd  = ifelse(state == "blank", NA, sd(plasma_power_watt, na.rm = T)),
         plasma_power_rsd      = ifelse(state == "blank", NA, plasma_power_watt_sd / plasma_power_watt_avg),
         .after = plasma_power_watt) %>%
  ungroup()

# Take average power level, SD and RSD

plasma_power_avg <- data %>%
  filter(state == "plasma") %>%
  pull(plasma_power_watt_avg) %>%
  unique()

plasma_power_sd <- data %>%
  filter(state == "plasma") %>%
  pull(plasma_power_watt_sd) %>%
  unique()

plasma_power_rsd <- data %>%
  filter(state == "plasma") %>%
  pull(plasma_power_rsd) %>%
  unique()

# Take CO2 flow in to calculate SEI

flow_co2 <- data %>%
  filter(compound == "CO2") %>%
  pull(flow_mlmin) %>%
  unique()

flow_co2_sd <- data %>%
  filter(compound == "CO2") %>%
  pull(flow_mlmin_sd) %>%
  unique()

flow_co2_rsd <- data %>%
  filter(compound == "CO2") %>%
  pull(flow_rsd) %>%
  unique()

# Calculate SEI (J/mmol same as kJ/mol) (molar gas volume at 1 atm & 20°C)

sei <- (plasma_power_avg / flow_co2) * 60 * 24.055

# Calculate SEI RSD

sei_rsd <- sqrt(plasma_power_rsd ^ 2 + flow_co2_rsd ^ 2)

# Calculate SEI SD

sei_sd <- sei_rsd * sei

# Adding values to the data

data <- mutate(data,
               sei_kjmol    = ifelse(state == "plasma", sei, NA),
               sei_kjmol_sd = ifelse(state == "plasma", sei_sd, NA),
               sei_rsd      = ifelse(state == "plasma", sei_rsd, NA),
               .after = plasma_power_rsd)

#####################
# Energy efficiency #
#####################

# Plasma temperature (K) now set at 200°C

plasma_temp_kelv <- 273.15 + unique(data$plasma_temp_celc)

# Gibbs Free Enthalpy of Formation of CO in function of gas temperature (sixth order polynomial fit from NIST-JANAF data)

gf_co <- -1.48747E-20*(plasma_temp_kelv ^ 6) + 2.90543E-16* (plasma_temp_kelv ^ 5) - 2.18412E-12 * (plasma_temp_kelv ^ 4) + 7.80039E-09 * (plasma_temp_kelv ^ 3) - 1.14364E-05 * (plasma_temp_kelv ^ 2) - 8.19286E-02 * plasma_temp_kelv - 1.12455E+02

# Gibbs Free Enthalpy of Formation of CO2 in function of gas temperature (sixth order polynomial fit from NIST-JANAF data)

gf_co2 <- 1.21850E-21* (plasma_temp_kelv ^ 6) - 2.63973E-17 * (plasma_temp_kelv ^ 5) + 2.25893E-13 * (plasma_temp_kelv ^ 4) - 9.56091E-10 * (plasma_temp_kelv ^ 3) + 2.75906E-06 * (plasma_temp_kelv ^ 2) - 4.68102E-03 * plasma_temp_kelv - 3.93205E+02

# Energy efficiency (%) based on the Gibbs free enthalpies of formation of reactant and products (used in scientific settings)

ee_gf_perc <-  ((alpha * conc_avg_corr_co * gf_co) - (conv_co2 * conc_avg_corr_co2_blank * gf_co2)) / (sei) * 100

ee_gf_rsd <- sqrt(sei_rsd ^ 2 +
                  (((alpha_rsd ^ 2 + conc_avg_corr_co_rsd ^ 2) *
                      (alpha * conc_avg_corr_co * gf_co) ^ 2 +
                      (conv_co2_rsd ^ 2 + conc_avg_corr_co2_blank_rsd ^ 2) *
                    (conv_co2 * conc_avg_corr_co2_blank * gf_co2) ^ 2) /
                   (alpha * conc_avg_corr_co * gf_co - conv_co2 * conc_avg_corr_co2_blank * gf_co2) ^ 2))

ee_gf_perc_sd <- ee_gf_rsd * ee_gf_perc

data <- mutate(data,
               ee_gf_perc    = ifelse(state == "plasma", ee_gf_perc, NA),
               ee_gf_perc_sd = ifelse(state == "plasma", ee_gf_perc_sd, NA),
               ee_gf_rsd     = ifelse(state == "plasma", ee_gf_rsd, NA),
               .after = plasma_temp_celc)

# Energy efficiency (%) based on the Lower Heating Values of the products and reactants (a metric for the amount of energy one can obtain by combusting the products), used mainly in the oil industry

ee_lhv_perc <- (alpha * conc_avg_corr_co * 0.323) / sei * 100

ee_lhv_rsd <- sqrt(sei_rsd ^ 2 + (alpha_rsd ^ 2 + conc_avg_corr_co_rsd ^ 2))

ee_lhv_perc_sd <- ee_lhv_rsd * ee_lhv_perc

data <- mutate(data,
               ee_lhv_perc    = ifelse(state == "plasma", ee_lhv_perc, NA),
               ee_lhv_perc_sd = ifelse(state == "plasma", ee_lhv_perc_sd, NA),
               ee_lhv_rsd     = ifelse(state == "plasma", ee_lhv_rsd, NA),
               .after = ee_gf_rsd)

# Energy efficiency (%) based on the Higher Heating Values of the products and reactants (a metric for the amount of energy one can obtain by combusting the products), used mainly in the oil industry
# LHV and HHV values for CO are the same

ee_hhv_perc <- (alpha * conc_avg_corr_co * 0.323) / sei * 100

ee_hhv_rsd <- sqrt(sei_rsd ^ 2 + (alpha_rsd ^ 2 + conc_avg_corr_co_rsd ^ 2))

ee_hhv_perc_sd <- ee_hhv_rsd * ee_hhv_perc

data <- mutate(data,
               ee_hhv_perc    = ifelse(state == "plasma", ee_hhv_perc, NA),
               ee_hhv_perc_sd = ifelse(state == "plasma", ee_hhv_perc_sd, NA),
               ee_hhv_rsd     = ifelse(state == "plasma", ee_hhv_rsd, NA),
               .after = ee_lhv_rsd)

#################################################
# Calculate CO2 conversion using Snoeckx method #
#################################################

# X_CO2 = X_GC / ( ( 1 + gamma / 2 ) - ( gamma / 2 ) * X_GC )
# with gamma = ( co2flow ) / ( n2flow + co2flow )
# and X_GC = 1 - c_GC,plasma / c_GC,blank

# Calculate gamma

gamma <- conc_avg_co2_blank / (conc_avg_co2_blank + conc_avg_n2_blank)

# Calculate the CO2 conversion measured by GC (no corrections)

conc_sd_co2_blank <- data %>%
  filter(state == "blank" & compound == "CO2") %>%
  pull(conc_sd) %>%
  unique()

conc_rsd_co2_blank <- data %>%
  filter(state == "blank" & compound == "CO2") %>%
  pull(conc_rsd) %>%
  unique()

conc_avg_co2_plasma <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  pull(conc_avg) %>%
  unique()

conc_sd_co2_plasma <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  pull(conc_sd) %>%
  unique()

conc_rsd_co2_plasma <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  pull(conc_rsd) %>%
  unique()

# Calculation of incorrect conversion simply based on GC results

conv_co2_gc <- 1 - (conc_avg_co2_plasma / conc_avg_co2_blank)

conv_co2_gc_rsd <- sqrt(conc_rsd_co2_blank ^ 2 + conc_rsd_co2_plasma ^ 2)

conv_co2_gc_sd <- conv_co2_gc_rsd * conv_co2_gc

# Calculation of the CO2 conversion according to the method by Snoeckx

conv_co2_snoeckx <- conv_co2_gc / ((1 + gamma / 2) - (gamma / 2) * conv_co2_gc)

conv_co2_snoeckx_rsd <- sqrt(
  conv_co2_gc_rsd ^ 2 +
  ((conv_co2_gc_rsd * (gamma / 2) * conv_co2_gc) / ((1 + gamma / 2) - (gamma / 2) * conv_co2_gc)) ^ 2
  )

conv_co2_snoeckx_sd <- conv_co2_snoeckx_rsd * conv_co2_snoeckx

# Add data to framework

data <- mutate(data,
               conv_snoeckx     = ifelse(state == "plasma" & compound == "CO2", conv_co2_snoeckx, NA),
               conv_snoeckx_sd  = ifelse(state == "plasma" & compound == "CO2", conv_co2_snoeckx_sd, NA),
               conv_snoeckx_rsd = ifelse(state == "plasma" & compound == "CO2", conv_co2_snoeckx_rsd, NA),
               .after = ee_hhv_rsd)

# delta can be calculated from this and performs the same role of alpha in the general method

delta <- 1 + conv_co2_snoeckx / 2

delta_sd <- 0

delta_rsd <- 0

###########################################
# Selectivity & Yield in Snoeckx's method #
###########################################

###################
# Carbon Monoxide #
###################

# Carbon selectivity #
######################

conc_avg_co_plasma <- data %>%
  filter(state == "plasma" & compound == "CO") %>%
  pull(conc_avg) %>%
  unique()

conc_sd_co_plasma <- data %>%
  filter(state == "plasma" & compound == "CO") %>%
  pull(conc_sd) %>%
  unique()

conc_rsd_co_plasma <- data %>%
  filter(state == "plasma" & compound == "CO") %>%
  pull(conc_rsd) %>%
  unique()

selec_c_co <- (delta * conc_avg_co_plasma) / (conc_avg_co2_blank - delta * conc_avg_co2_plasma)

selec_c_co_rsd <- sqrt(
  conc_rsd_co_plasma ^ 2
  +
  (conc_sd_co2_blank^2 + delta ^ 2 * conc_sd_co2_plasma ^ 2)/(conc_avg_co2_blank - delta * conc_avg_co2_plasma)^2
)

selec_c_co_sd <- selec_c_co_rsd * selec_c_co

data <- mutate(data,
               selec_c     = ifelse(compound == "CO" & state == "plasma", selec_c_co, NA),
               selec_c_sd  = ifelse(compound == "CO" & state == "plasma", selec_c_co_sd, NA),
               selec_c_rsd = ifelse(compound == "CO" & state == "plasma", selec_c_co_rsd, NA),
               .after = conv_rsd)

# Carbon yield #
################

yield_c_co <- selec_c_co * conv_co2

yield_c_co_rsd <- sqrt(selec_c_co_rsd ^ 2 + conv_co2_rsd ^ 2)

yield_c_co_sd <- yield_c_co_rsd * yield_c_co

data <- mutate(data,
               yield_c     = ifelse(compound == "CO" & state == "plasma", yield_c_co, NA),
               yield_c_sd  = ifelse(compound == "CO" & state == "plasma", yield_c_co_sd, NA),
               yield_c_rsd = ifelse(compound == "CO" & state == "plasma", yield_c_co_rsd, NA),
               .after = selec_c_rsd)

# Oxygen selectivity #
######################

selec_o_co <- (delta * conc_avg_co_plasma) / (2 * (conc_avg_co2_blank - delta * conc_avg_co2_plasma))

selec_o_co_rsd <- sqrt(
  conc_rsd_co_plasma ^ 2
  +
  (conc_sd_co2_blank^2 + delta ^ 2 * conc_sd_co2_plasma ^ 2)/(conc_avg_co2_blank - delta * conc_avg_co2_plasma)^2
)

selec_o_co_sd <- selec_o_co_rsd * selec_o_co

data <- mutate(data,
               selec_o     = ifelse(compound == "CO" & state == "plasma", selec_o_co, NA),
               selec_o_sd  = ifelse(compound == "CO" & state == "plasma", selec_o_co_sd, NA),
               selec_o_rsd = ifelse(compound == "CO" & state == "plasma", selec_o_co_rsd, NA),
               .after = yield_c_rsd)

# Oxygen yield #
################

yield_o_co <- selec_o_co * conv_co2

yield_o_co_rsd <- sqrt(selec_o_co_rsd ^ 2 + conv_co2_rsd ^ 2)

yield_o_co_sd <- yield_o_co_rsd * yield_o_co

data <- mutate(data,
               yield_o     = ifelse(compound == "CO" & state == "plasma", yield_o_co, NA),
               yield_o_sd  = ifelse(compound == "CO" & state == "plasma", yield_o_co_sd, NA),
               yield_o_rsd = ifelse(compound == "CO" & state == "plasma", yield_o_co_rsd, NA),
               .after = selec_o_rsd)

##########
# Oxygen #
##########

# Oxygen selectivity #
######################

conc_avg_o2_plasma <- data %>%
  filter(state == "plasma" & compound == "O2") %>%
  pull(conc_avg) %>%
  unique()

conc_sd_o2_plasma <- data %>%
  filter(state == "plasma" & compound == "O2") %>%
  pull(conc_sd) %>%
  unique()

conc_rsd_o2_plasma <- data %>%
  filter(state == "plasma" & compound == "O2") %>%
  pull(conc_rsd) %>%
  unique()

selec_o_o2 <- (delta * conc_avg_o2_plasma) / (conc_avg_co2_blank - delta * conc_avg_co2_plasma)

selec_o_o2_rsd <- sqrt(
  conc_rsd_o2_plasma ^ 2
  +
  (conc_sd_co2_blank^2 + delta ^ 2 * conc_sd_co2_plasma ^ 2)/(conc_avg_co2_blank - delta * conc_avg_co2_plasma)^2
)

selec_o_o2_sd <- selec_o_co_rsd * selec_o_co

data <- mutate(data,
               selec_o     = ifelse(compound == "O2" & state == "plasma", selec_o_co, selec_o),
               selec_o_sd  = ifelse(compound == "O2" & state == "plasma", selec_o_co_sd, selec_o_sd),
               selec_o_rsd = ifelse(compound == "O2" & state == "plasma", selec_o_co_rsd, selec_o_rsd))

# Oxygen yield #
################

yield_o_o2 <- selec_o_o2 * conv_co2

yield_o_o2_rsd <- sqrt(selec_o_o2_rsd ^ 2 + conv_co2_rsd ^ 2)

yield_o_o2_sd <- yield_o_o2_rsd * yield_o_o2

data <- mutate(data,
               yield_o     = ifelse(compound == "O2" & state == "plasma", yield_o_o2, yield_o),
               yield_o_sd  = ifelse(compound == "O2" & state == "plasma", yield_o_o2_sd, yield_o_sd),
               yield_o_rsd = ifelse(compound == "O2" & state == "plasma", yield_o_o2_rsd, yield_o_rsd))

#######################################
# Old selectivity & yield calculation #
#######################################

selec_c_co_snoeckx <- 1
selec_o_co_snoeckx <- .5
selec_o_o2_snoeckx <- .5

yield_c_co_snoeckx <- selec_c_co_snoeckx * conv_co2_snoeckx
yield_o_co_snoeckx <- selec_o_co_snoeckx * conv_co2_snoeckx
yield_o_o2_snoeckx <- selec_o_o2_snoeckx * conv_co2_snoeckx

data <- mutate(data,
               selec_c_snoeckx = ifelse(state == "plasma" & compound == "CO", selec_c_co_snoeckx, NA),
               selec_o_snoeckx = ifelse(state == "plasma" & compound == "CO", selec_o_co_snoeckx, NA),
               selec_o_snoeckx = ifelse(state == "plasma" & compound == "O2", selec_o_o2_snoeckx, selec_o_snoeckx),
               yield_c_snoeckx = ifelse(state == "plasma" & compound == "CO", yield_c_co_snoeckx, NA),
               yield_o_snoeckx = ifelse(state == "plasma" & compound == "CO", yield_o_co_snoeckx, NA),
               yield_o_snoeckx = ifelse(state == "plasma" & compound == "O2", yield_o_o2_snoeckx, yield_o_snoeckx),
               .after = conv_snoeckx_rsd)

######################################
# Energy efficiency Snoeckx's method #
######################################

ee_gf_snoeckx_perc <- ((gf_co - gf_co2) * conv_co2_snoeckx) / sei * 100

ee_gf_snoeckx_rsd <- sqrt(conv_co2_snoeckx_rsd ^ 2 + sei_rsd ^ 2)

ee_gf_snoeckx_perc_sd <- ee_gf_snoeckx_rsd * ee_gf_snoeckx_perc

data <- mutate(data,
               ee_gf_snoeckx_perc    = ifelse(state == "plasma", ee_gf_snoeckx_perc, NA),
               ee_gf_snoeckx_perc_sd = ifelse(state == "plasma", ee_gf_snoeckx_perc_sd, NA),
               ee_gf_snoeckx_rsd     = ifelse(state == "plasma", ee_gf_snoeckx_rsd, NA),
               .after = conv_snoeckx_rsd)

##############################################################################################
# Calculate difference between the two methods and test if there is a significant difference #
##############################################################################################

# t-test with known means and standard deviations

# m1, m2: the sample means
# s1, s2: the sample standard deviations
# n1, n2: the same sizes
# m0: the null value for the difference in means to be tested for. Default is 0. 
# equal.variance: whether or not to assume equal variance. Default is FALSE. 
t.test2 <- function(m1,m2,s1,s2,n1,n2,m0=0,equal.variance=FALSE)
{
  if( equal.variance==FALSE ) 
  {
    se <- sqrt( (s1^2/n1) + (s2^2/n2) )
    # welch-satterthwaite df
    df <- ( (s1^2/n1 + s2^2/n2)^2 )/( (s1^2/n1)^2/(n1-1) + (s2^2/n2)^2/(n2-1) )
  } else
  {
    # pooled standard deviation, scaled by the sample sizes
    se <- sqrt( (1/n1 + 1/n2) * ((n1-1)*s1^2 + (n2-1)*s2^2)/(n1+n2-2) ) 
    df <- n1+n2-2
  }      
  t <- (m1-m2-m0)/se 
  dat <- c(m1-m2, se, t, 2*pt(-abs(t),df))    
  names(dat) <- c("Difference of means", "Std Error", "t", "p-value")
  return(dat) 
}

num_msrmnts <- data %>%
  filter(state=="blank" & compound == "N2") %>%
  nrow()

t_test_result <- t.test2(m1=conv_co2, m2=conv_co2_snoeckx, s1=conv_co2_sd, s2=conv_co2_snoeckx_sd, n1=num_msrmnts, n2=num_msrmnts)

data <- mutate(data,
               p_value = t_test_result[4],
               t_test_result = ifelse(t_test_result[4] <= .05, "Null hypothesis is rejected (p value <= .05), difference in results from methods is significant", "null hypothesis is accepted (p value > .05), difference in results from methods is insignificant") )

############################################
# Write the calculated data to a .csv file #
############################################

write_csv(data, gsub(".csv", "-calc.csv", filename))
```

---
title: "CO$_{2}$ Splitting - Experimental Report"
subtitle: "Material: `r unique(data$material)`, residence time: `r unique(data$res_time_sec)`s & plasma power: `r data %>% filter(state == "plasma") %>% select(plasma_power_watt_avg) %>% unique() %>% round(digits = 2)`W"
author: "Sander Bossier"
date: "`r Sys.time()`"
---

# Conversion

```{r echo = F}
conv_co2_table <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  select("Compound"                        = compound,
         "Conversion (%)"                  = conv,
         "Standard deviation (%)"          = conv_sd,
         "Relative standard deviation (%)" = conv_rsd) %>%
  unique()
conv_co2_table[-1] <- conv_co2_table[-1] * 100
kable(conv_co2_table, digits = 2)
```

# Elements

## Carbon (C)

```{r echo = F}
balance_c_table <- data %>%
  select("Carbon Balance"                  = balance_c,
         "Standard deviation"              = balance_c_sd,
         "Relative standard deviation (%)" = balance_c_rsd) %>%
  unique()
balance_c_table[3] <- balance_c_table[3]*100
kable(balance_c_table, digits = 2)
```

```{r echo = F}
element_c_table <- data %>%
  filter(state == "plasma" & grepl('C', compound) & compound != "CO2") %>%
  select("Compound"               = compound,
         "C selectivity (%)" = selec_c,
         "C select. SD (%)"       = selec_c_sd,
         "C select. RSD (%)"      = selec_c_rsd,
         "C yield (%)"       = yield_c,
         "C yield SD (%)"         = yield_c_sd,
         "C yield RSD (%)"        = yield_c_rsd) %>%
  unique()
element_c_table[-1] <- element_c_table[-1] * 100
kable(element_c_table, digits = 2)
```

## Oxygen (O)

```{r echo = F}
balance_o_table <- data %>%
  select("Oxygen Balance"                  = balance_o,
         "Standard deviation"              = balance_o_sd,
         "Relative standard deviation (%)" = balance_o_rsd) %>%
  unique()
balance_o_table[3] <- balance_o_table[3]*100
kable(balance_o_table, digits = 2)
```

```{r echo = F}
element_o_table <- data %>%
  filter(state == "plasma" & grepl('O', compound) & compound != "CO2") %>%
  select("Compound"               = compound,
         "O selectivity (%)" = selec_o,
         "O select. SD (%)"       = selec_o_sd,
         "O select. RSD (%)"      = selec_o_rsd,
         "O yield (%)"       = yield_o,
         "O yield SD (%)"         = yield_o_sd,
         "O yield RSD (%)"        = yield_o_rsd) %>%
  unique()
element_o_table[-1] <- element_o_table[-1] * 100
kable(element_o_table, digits = 2)
```

# Energy Efficiency

```{r echo = F}
ee_table <- tibble(BasedOn = c("Gibbs Free Energy of Formation", "Lower Heating Value (LHV)", "Higher Heating Value (HHV)"))
ee_table$Value <- c(ee_gf_perc, ee_lhv_perc, ee_hhv_perc)
ee_table$SD <- c(ee_gf_perc_sd, ee_lhv_perc_sd, ee_hhv_perc_sd)
ee_table$RSD <- c(ee_gf_rsd*100, ee_lhv_rsd*100, ee_hhv_perc_sd*100)
colnames(ee_table) <- c("Energy Efficiency Based On", "Value (%)", "Standard Deviation (%)", "Relative Standard Deviation (%)")

kable(ee_table, digits = 3)
```

# Snoeckx's method

```{r echo = F}
conv_co2_snoeckx_table <- data %>%
  filter(state == "plasma" & compound == "CO2") %>%
  select("Compound"                        = compound,
         "Conversion (%)"                  = conv_snoeckx,
         "Standard deviation (%)"          = conv_snoeckx_sd,
         "Relative standard deviation (%)" = conv_snoeckx_rsd) %>%
  unique()
conv_co2_snoeckx_table[-1] <- conv_co2_snoeckx_table[-1] * 100
kable(conv_co2_snoeckx_table, digits = 2)

element_c_snoeckx_table <- data %>%
  filter(state == "plasma" & grepl('C', compound) & compound != "CO2") %>%
  select("Compound"          = compound,
         "C selectivity (%)" = selec_c_snoeckx,
         "C yield (%)"       = yield_c_snoeckx) %>%
  unique()
element_c_snoeckx_table[-1] <- element_c_snoeckx_table[-1] * 100
kable(element_c_snoeckx_table, digits = 2)

element_o_snoeckx_table <- data %>%
  filter(state == "plasma" & grepl('O', compound) & compound != "CO2") %>%
  select("Compound"          = compound,
         "O selectivity (%)" = selec_o_snoeckx,
         "O yield (%)"       = yield_o_snoeckx) %>%
  unique()
element_o_snoeckx_table[-1] <- element_o_snoeckx_table[-1] * 100
kable(element_o_snoeckx_table, digits = 2)

ee_snoeckx_table <- tibble(based_on = c("Gibbs Free Energy of Formation"))
ee_snoeckx_table$value <- c(ee_gf_snoeckx_perc)
ee_snoeckx_table$sd <- c(ee_gf_snoeckx_perc_sd)
ee_snoeckx_table$rsd <- c(ee_gf_snoeckx_rsd*100)
colnames(ee_snoeckx_table) <- c("Energy Efficiency Based On", "Value (%)", "Standard Deviation (%)", "Relative Standard Deviation (%)")
kable(ee_snoeckx_table, digits = 3)
```

# Experimental Parameters

```{r echo = F}
flow_n2 <- data %>%
  filter(compound == "N2") %>%
  pull(flow_mlmin) %>%
  unique()

flow_n2_sd <- data %>%
  filter(compound == "N2") %>%
  pull(flow_mlmin_sd) %>%
  unique()

flow_n2_rsd <- data %>%
  filter(compound == "N2") %>%
  pull(flow_rsd) %>%
  unique()

beta_theoretical     <- flow_n2 / flow_co2
beta_theoretical_sd  <- 0
beta_theoretical_rsd <- 0

epx_par_table <- tibble(Parameter = c("Flow rate N2 (mL/min)", "Flow rate CO2 (mL/min)", "Alpha", "Beta", "Beta (theoretical)", "Plasma Power (W)", "SEI (kJ/mol)", "Yield Ratio CO:O2", "# Measurements", "Plasma Temp (°C)"))
epx_par_table$Value <- c(flow_n2, flow_co2, alpha, beta, beta_theoretical, plasma_power_avg, sei, yield_ratio, num_msrmnts, plasma_temp_kelv-273.15)
epx_par_table$SD <- c(flow_n2_sd, flow_co2_sd, alpha_sd, beta_sd, beta_theoretical_sd, plasma_power_sd, sei_sd, yield_ratio_sd, 0, 0)
epx_par_table$RSD <- c(flow_n2_rsd*100, flow_co2_rsd*100, alpha_rsd*100, beta_rsd*100, beta_theoretical_rsd*100, plasma_power_rsd*100, sei_rsd*100, yield_ratio_rsd*100, 0, 0)
colnames(epx_par_table) <- c("Experimental Parameters", "Value", "Standard Deviation", "Relative Standard Deviation (%)")

kable(epx_par_table, digits = 2)
```
